"""initial schema

Revision ID: 1e6cb8994a20
Revises: 
Create Date: 2026-08-25 10:10:15.016837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e6cb8994a20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('evidence_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_family', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_bucket', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_path', sa.String(length=512), nullable=True),
    sa.Column('extracted_claims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', 'observed_bucket', name='uq_source_content_bucket'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_external_id')
    )
    op.create_index(op.f('ix_evidence_events_content_hash'), 'evidence_events', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_events_external_id'), 'evidence_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_evidence_events_observed_at'), 'evidence_events', ['observed_at'], unique=False)
    op.create_index(op.f('ix_evidence_events_source_family'), 'evidence_events', ['source_family'], unique=False)
    op.create_index(op.f('ix_evidence_events_source_id'), 'evidence_events', ['source_id'], unique=False)
    op.create_index('ix_evidence_source_observed', 'evidence_events', ['source_id', 'observed_at'], unique=False)
    op.create_table('organizations',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('official_domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('github_orgs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('social_handles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('claimed_locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('foundation_form', sa.String(length=128), nullable=True),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organizations_display_name'), 'organizations', ['display_name'], unique=False)
    op.create_table('source_cursors',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('safe_sha', sa.String(length=64), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('chain_products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('purpose_labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stack_family', sa.String(length=64), nullable=False),
    sa.Column('stack_details', sa.String(length=128), nullable=True),
    sa.Column('layer', sa.String(length=32), nullable=True),
    sa.Column('parent_chain', sa.String(length=128), nullable=True),
    sa.Column('settlement_chain', sa.String(length=128), nullable=True),
    sa.Column('da_layer', sa.String(length=128), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('current_score_id', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain_first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registry_pr_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registry_merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('testnet_announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mainnet_announced_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mainnet_live_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_score_id'], ['score_snapshots.id'], name='fk_chain_current_score', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_products_canonical_name'), 'chain_products', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_chain_products_first_seen_at'), 'chain_products', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_chain_products_organization_id'), 'chain_products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chain_products_slug'), 'chain_products', ['slug'], unique=True)
    op.create_index(op.f('ix_chain_products_stack_family'), 'chain_products', ['stack_family'], unique=False)
    op.create_index(op.f('ix_chain_products_stage'), 'chain_products', ['stage'], unique=False)
    op.create_table('africa_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('intent_label', sa.String(length=32), nullable=False),
    sa.Column('readiness', sa.Float(), nullable=False),
    sa.Column('whitespace', sa.Float(), nullable=False),
    sa.Column('countries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('regions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rails_use_cases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explicit_geo_score', sa.Float(), nullable=False),
    sa.Column('regional_action_score', sa.Float(), nullable=False),
    sa.Column('use_case_fit_score', sa.Float(), nullable=False),
    sa.Column('whitespace_score', sa.Float(), nullable=False),
    sa.Column('contactability_score', sa.Float(), nullable=False),
    sa.Column('operating_capacity_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('analyst_override', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_africa_assessments_candidate_id'), 'africa_assessments', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_africa_assessments_intent_label'), 'africa_assessments', ['intent_label'], unique=False)
    op.create_table('alert_dispatches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_detail', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_candidate_dispatched', 'alert_dispatches', ['candidate_id', 'dispatched_at'], unique=False)
    op.create_index(op.f('ix_alert_dispatches_alert_type'), 'alert_dispatches', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_dispatches_candidate_id'), 'alert_dispatches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_alert_dispatches_dedup_key'), 'alert_dispatches', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alert_dispatches_dispatched_at'), 'alert_dispatches', ['dispatched_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('role_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('channel_value', sa.String(length=512), nullable=False),
    sa.Column('channel_hash', sa.String(length=64), nullable=False),
    sa.Column('permitted_purpose', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_candidate_id'), 'contacts', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_contacts_channel_hash'), 'contacts', ['channel_hash'], unique=False)
    op.create_index(op.f('ix_contacts_org_id'), 'contacts', ['org_id'], unique=False)
    op.create_index(op.f('ix_contacts_role_type'), 'contacts', ['role_type'], unique=False)
    op.create_index(op.f('ix_contacts_suppressed'), 'contacts', ['suppressed'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('chain_product_id', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('caip2', sa.String(length=128), nullable=True),
    sa.Column('protocol_namespace', sa.String(length=64), nullable=True),
    sa.Column('human_chain_id', sa.String(length=64), nullable=True),
    sa.Column('rpc_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explorer_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('faucet_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('launch_claims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_product_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_caip2'), 'networks', ['caip2'], unique=False)
    op.create_index(op.f('ix_networks_chain_product_id'), 'networks', ['chain_product_id'], unique=False)
    op.create_index(op.f('ix_networks_environment'), 'networks', ['environment'], unique=False)
    op.create_index(op.f('ix_networks_human_chain_id'), 'networks', ['human_chain_id'], unique=False)
    op.create_table('observation_links',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('link_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_links_candidate_id'), 'observation_links', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_observation_links_evidence_id'), 'observation_links', ['evidence_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_type', sa.String(length=64), nullable=False),
    sa.Column('geography', sa.String(length=128), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_active'), 'opportunities', ['active'], unique=False)
    op.create_index(op.f('ix_opportunities_candidate_id'), 'opportunities', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('related_candidate_id', sa.String(length=64), nullable=True),
    sa.Column('match_weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.String(length=64), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'candidate_id', 'related_candidate_id', 'status', name='uq_open_review_task')
    )
    op.create_index(op.f('ix_review_tasks_candidate_id'), 'review_tasks', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_created_at'), 'review_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_tasks_related_candidate_id'), 'review_tasks', ['related_candidate_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_review_tasks_task_type'), 'review_tasks', ['task_type'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=False),
    sa.Column('africa_fit', sa.Float(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('radar_score', sa.Float(), nullable=False),
    sa.Column('outreach_score', sa.Float(), nullable=False),
    sa.Column('outreach_qualified', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('workflow_state', sa.String(length=32), nullable=False),
    sa.Column('feature_vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshots_calculated_at'), 'score_snapshots', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_score_snapshots_candidate_id'), 'score_snapshots', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_score_snapshots_outreach_qualified'), 'score_snapshots', ['outreach_qualified'], unique=False)
    op.create_index(op.f('ix_score_snapshots_outreach_score'), 'score_snapshots', ['outreach_score'], unique=False)
    op.create_index(op.f('ix_score_snapshots_radar_score'), 'score_snapshots', ['radar_score'], unique=False)
    op.create_index(op.f('ix_score_snapshots_state'), 'score_snapshots', ['state'], unique=False)
    op.create_index(op.f('ix_score_snapshots_workflow_state'), 'score_snapshots', ['workflow_state'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('lifecycle_implication', sa.String(length=64), nullable=True),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_active'), 'signals', ['active'], unique=False)
    op.create_index(op.f('ix_signals_candidate_id'), 'signals', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('network_incarnations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('network_id', sa.String(length=64), nullable=False),
    sa.Column('genesis_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('genesis_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block0_hash', sa.String(length=128), nullable=True),
    sa.Column('first_observed_height', sa.Integer(), nullable=True),
    sa.Column('last_observed_height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=64), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'genesis_fingerprint', name='uq_network_genesis')
    )
    op.create_index(op.f('ix_network_incarnations_genesis_fingerprint'), 'network_incarnations', ['genesis_fingerprint'], unique=False)
    op.create_index(op.f('ix_network_incarnations_network_id'), 'network_incarnations', ['network_id'], unique=False)
    op.create_index(op.f('ix_network_incarnations_status'), 'network_incarnations', ['status'], unique=False)
    op.create_table('verification_observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('network_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('probe_round', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_class', sa.String(length=32), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('identity_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('chain_id', sa.String(length=64), nullable=True),
    sa.Column('genesis_hash', sa.String(length=128), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('client_version', sa.String(length=255), nullable=True),
    sa.Column('raw_observation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_candidate_observed', 'verification_observations', ['candidate_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_verification_observations_candidate_id'), 'verification_observations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_verification_observations_endpoint_hash'), 'verification_observations', ['endpoint_hash'], unique=False)
    op.create_index(op.f('ix_verification_observations_failure_class'), 'verification_observations', ['failure_class'], unique=False)
    op.create_index(op.f('ix_verification_observations_identity_fingerprint'), 'verification_observations', ['identity_fingerprint'], unique=False)
    op.create_index(op.f('ix_verification_observations_network_id'), 'verification_observations', ['network_id'], unique=False)
    op.create_index(op.f('ix_verification_observations_observed_at'), 'verification_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_verification_observations_success'), 'verification_observations', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_observations_success'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_observed_at'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_network_id'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_identity_fingerprint'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_failure_class'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_endpoint_hash'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_candidate_id'), table_name='verification_observations')
    op.drop_index('ix_verification_candidate_observed', table_name='verification_observations')
    op.drop_table('verification_observations')
    op.drop_index(op.f('ix_network_incarnations_status'), table_name='network_incarnations')
    op.drop_index(op.f('ix_network_incarnations_network_id'), table_name='network_incarnations')
    op.drop_index(op.f('ix_network_incarnations_genesis_fingerprint'), table_name='network_incarnations')
    op.drop_table('network_incarnations')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_candidate_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_active'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_score_snapshots_workflow_state'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_state'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_radar_score'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_outreach_score'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_outreach_qualified'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_candidate_id'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_calculated_at'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index(op.f('ix_review_tasks_task_type'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_related_candidate_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_created_at'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_candidate_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_candidate_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_active'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_observation_links_evidence_id'), table_name='observation_links')
    op.drop_index(op.f('ix_observation_links_candidate_id'), table_name='observation_links')
    op.drop_table('observation_links')
    op.drop_index(op.f('ix_networks_human_chain_id'), table_name='networks')
    op.drop_index(op.f('ix_networks_environment'), table_name='networks')
    op.drop_index(op.f('ix_networks_chain_product_id'), table_name='networks')
    op.drop_index(op.f('ix_networks_caip2'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_contacts_suppressed'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_role_type'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_org_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_channel_hash'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_candidate_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_alert_dispatches_dispatched_at'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_alert_dispatches_dedup_key'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_alert_dispatches_candidate_id'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_alert_dispatches_alert_type'), table_name='alert_dispatches')
    op.drop_index('ix_alert_candidate_dispatched', table_name='alert_dispatches')
    op.drop_table('alert_dispatches')
    op.drop_index(op.f('ix_africa_assessments_intent_label'), table_name='africa_assessments')
    op.drop_index(op.f('ix_africa_assessments_candidate_id'), table_name='africa_assessments')
    op.drop_table('africa_assessments')
    op.drop_index(op.f('ix_chain_products_stage'), table_name='chain_products')
    op.drop_index(op.f('ix_chain_products_stack_family'), table_name='chain_products')
    op.drop_index(op.f('ix_chain_products_slug'), table_name='chain_products')
    op.drop_index(op.f('ix_chain_products_organization_id'), table_name='chain_products')
    op.drop_index(op.f('ix_chain_products_first_seen_at'), table_name='chain_products')
    op.drop_index(op.f('ix_chain_products_canonical_name'), table_name='chain_products')
    op.drop_table('chain_products')
    op.drop_table('source_cursors')
    op.drop_index(op.f('ix_organizations_display_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_evidence_source_observed', table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_source_id'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_source_family'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_observed_at'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_external_id'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_content_hash'), table_name='evidence_events')
    op.drop_table('evidence_events')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
