"""activity snapshots and funding rounds

Revision ID: 8aa8dd72954a
Revises: 0003_chain_slug_org
Create Date: 2026-08-25 10:47:40.609187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aa8dd72954a'
down_revision: Union[str, Sequence[str], None] = '0003_chain_slug_org'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('channel_ref', sa.String(length=512), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_kind', sa.String(length=64), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('contributors', sa.Integer(), nullable=True),
    sa.Column('commits_last_30d', sa.Integer(), nullable=True),
    sa.Column('releases_last_90d', sa.Integer(), nullable=True),
    sa.Column('posts_last_30d', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('extra_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_candidate_channel', 'activity_snapshots', ['candidate_id', 'channel', 'observed_at'], unique=False)
    op.create_index(op.f('ix_activity_snapshots_candidate_id'), 'activity_snapshots', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_activity_snapshots_channel'), 'activity_snapshots', ['channel'], unique=False)
    op.create_index(op.f('ix_activity_snapshots_last_activity_at'), 'activity_snapshots', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_activity_snapshots_observed_at'), 'activity_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_activity_snapshots_org_id'), 'activity_snapshots', ['org_id'], unique=False)
    op.create_table('funding_rounds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('round_type', sa.String(length=32), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_as_published', sa.String(length=64), nullable=True),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('investors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lead_investor', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['chain_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'round_type', 'amount_as_published', 'announced_at', name='uq_funding_round_event')
    )
    op.create_index('ix_funding_candidate_announced', 'funding_rounds', ['candidate_id', 'announced_at'], unique=False)
    op.create_index(op.f('ix_funding_rounds_announced_at'), 'funding_rounds', ['announced_at'], unique=False)
    op.create_index(op.f('ix_funding_rounds_candidate_id'), 'funding_rounds', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_funding_rounds_org_id'), 'funding_rounds', ['org_id'], unique=False)
    op.create_index(op.f('ix_funding_rounds_round_type'), 'funding_rounds', ['round_type'], unique=False)
    op.drop_index(op.f('ix_alert_dedup'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_chain_aliases_gin'), table_name='chain_products', postgresql_ops={'aliases': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_chain_name_trgm'), table_name='chain_products', postgresql_ops={'canonical_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_chain_purpose_gin'), table_name='chain_products', postgresql_ops={'purpose_labels': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_foreign_key('fk_chain_current_score', 'chain_products', 'score_snapshots', ['current_score_id'], ['id'], use_alter=True)
    op.drop_index(op.f('ix_contact_suppressed'), table_name='contacts', postgresql_where='(suppressed = true)')
    op.drop_index(op.f('uq_contact_channel_org'), table_name='contacts')
    op.drop_index(op.f('ix_evidence_claims_gin'), table_name='evidence_events', postgresql_ops={'extracted_claims': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_evidence_observed_brin'), table_name='evidence_events', postgresql_using='brin')
    op.drop_index(op.f('ix_network_caip2_lookup'), table_name='networks', postgresql_where='(caip2 IS NOT NULL)')
    op.drop_index(op.f('ix_org_aliases_gin'), table_name='organizations', postgresql_ops={'aliases': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_org_display_trgm'), table_name='organizations', postgresql_ops={'display_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_org_domains_gin'), table_name='organizations', postgresql_ops={'official_domains': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_org_github_gin'), table_name='organizations', postgresql_ops={'github_orgs': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_review_open'), table_name='review_tasks', postgresql_where="((status)::text = 'open'::text)")
    op.drop_index(op.f('ix_score_active_states'), table_name='score_snapshots', postgresql_where="((state)::text = ANY ((ARRAY['HOT'::character varying, 'QUALIFIED'::character varying])::text[]))")
    op.drop_index(op.f('ix_score_candidate_latest'), table_name='score_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_score_candidate_latest'), 'score_snapshots', ['candidate_id', sa.literal_column('calculated_at DESC')], unique=False)
    op.create_index(op.f('ix_score_active_states'), 'score_snapshots', ['state', sa.literal_column('outreach_score DESC')], unique=False, postgresql_where="((state)::text = ANY ((ARRAY['HOT'::character varying, 'QUALIFIED'::character varying])::text[]))")
    op.create_index(op.f('ix_review_open'), 'review_tasks', ['task_type', sa.literal_column('created_at DESC')], unique=False, postgresql_where="((status)::text = 'open'::text)")
    op.create_index(op.f('ix_org_github_gin'), 'organizations', ['github_orgs'], unique=False, postgresql_ops={'github_orgs': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_org_domains_gin'), 'organizations', ['official_domains'], unique=False, postgresql_ops={'official_domains': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_org_display_trgm'), 'organizations', ['display_name'], unique=False, postgresql_ops={'display_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_org_aliases_gin'), 'organizations', ['aliases'], unique=False, postgresql_ops={'aliases': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_network_caip2_lookup'), 'networks', ['caip2'], unique=False, postgresql_where='(caip2 IS NOT NULL)')
    op.create_index(op.f('ix_evidence_observed_brin'), 'evidence_events', ['observed_at'], unique=False, postgresql_using='brin')
    op.create_index(op.f('ix_evidence_claims_gin'), 'evidence_events', ['extracted_claims'], unique=False, postgresql_ops={'extracted_claims': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('uq_contact_channel_org'), 'contacts', ['channel_hash', sa.literal_column("COALESCE(org_id, ''::character varying)")], unique=True)
    op.create_index(op.f('ix_contact_suppressed'), 'contacts', ['channel_hash'], unique=False, postgresql_where='(suppressed = true)')
    op.drop_constraint('fk_chain_current_score', 'chain_products', type_='foreignkey')
    op.create_index(op.f('ix_chain_purpose_gin'), 'chain_products', ['purpose_labels'], unique=False, postgresql_ops={'purpose_labels': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_chain_name_trgm'), 'chain_products', ['canonical_name'], unique=False, postgresql_ops={'canonical_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_chain_aliases_gin'), 'chain_products', ['aliases'], unique=False, postgresql_ops={'aliases': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_alert_dedup'), 'alert_dispatches', ['dedup_key', sa.literal_column('dispatched_at DESC')], unique=False)
    op.drop_index(op.f('ix_funding_rounds_round_type'), table_name='funding_rounds')
    op.drop_index(op.f('ix_funding_rounds_org_id'), table_name='funding_rounds')
    op.drop_index(op.f('ix_funding_rounds_candidate_id'), table_name='funding_rounds')
    op.drop_index(op.f('ix_funding_rounds_announced_at'), table_name='funding_rounds')
    op.drop_index('ix_funding_candidate_announced', table_name='funding_rounds')
    op.drop_table('funding_rounds')
    op.drop_index(op.f('ix_activity_snapshots_org_id'), table_name='activity_snapshots')
    op.drop_index(op.f('ix_activity_snapshots_observed_at'), table_name='activity_snapshots')
    op.drop_index(op.f('ix_activity_snapshots_last_activity_at'), table_name='activity_snapshots')
    op.drop_index(op.f('ix_activity_snapshots_channel'), table_name='activity_snapshots')
    op.drop_index(op.f('ix_activity_snapshots_candidate_id'), table_name='activity_snapshots')
    op.drop_index('ix_activity_candidate_channel', table_name='activity_snapshots')
    op.drop_table('activity_snapshots')
    # ### end Alembic commands ###
