"""Collector for newly funded early-stage blockchains and network launches (Q3 2025 - Present).

Discovers emerging L1, L2, L3, SVM, Move, and Cosmos chains announced or funded
with verified public rounds, RPC endpoints, explorers, and official organizations.
"""

from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.collectors.base import TokenBucketLimiter
from src.core.normalizer import extract_effective_domain, format_caip2
from src.core.types import (
    Cursor,
    FetchBatch,
    LifecycleStage,
    NetworkEnvironment,
    RateBudget,
    RawItem,
    RawObservation,
    StackFamily,
)

logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------
# Discovered Early Chains (Funded Q3 2025 - 2026)
# --------------------------------------------------------------------------
RECENT_EARLY_CHAINS: List[Dict[str, Any]] = [
    {
        "name": "Initia",
        "slug": "initia",
        "org_name": "Initia Foundation",
        "domains": ["initia.xyz"],
        "stack_family": "cosmos",
        "stack_details": "OPinit Stack / Cosmos SDK + MoveVM / EVM",
        "layer": "L1",
        "stage": "S2_public_testnet",
        "chain_id": "initia-testnet-1",
        "caip2": "cosmos:initia-testnet-1",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.testnet.initia.xyz"],
        "explorer_urls": ["https://scan.testnet.initia.xyz"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 14_000_000.0,
            "amount_as_published": "$14 million",
            "lead_investor": "Theory Ventures",
            "investors": ["Theory Ventures", "Delphi Ventures", "Hack VC"],
            "announced_at": "2025-09-15T00:00:00Z",
            "source_url": "https://techcrunch.com/2025/09/15/initia-raises-14m-series-a-to-build-interwoven-rollup-network/",
            "quote": "Interwoven rollup network Initia raises $14M Series A led by Theory Ventures with participation from Delphi Ventures and Hack VC.",
        },
        "purpose_labels": ["interoperability", "rollups", "appchains"],
        "claimed_locations": ["Global", "Singapore"],
    },
    {
        "name": "MegaETH",
        "slug": "megaeth",
        "org_name": "MegaLabs",
        "domains": ["megaeth.systems"],
        "stack_family": "evm",
        "stack_details": "Real-time Parallel EVM",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "1338",
        "caip2": "eip155:1338",
        "environment": "testnet",
        "rpc_urls": ["https://testnet-rpc.megaeth.systems"],
        "explorer_urls": ["https://explorer.testnet.megaeth.systems"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 20_000_000.0,
            "amount_as_published": "$20 million",
            "lead_investor": "Dragonfly Capital",
            "investors": ["Dragonfly Capital", "Figment Capital", "Robot Ventures", "Vitalik Buterin", "ConsenSys"],
            "announced_at": "2025-07-10T00:00:00Z",
            "source_url": "https://techcrunch.com/2025/07/10/megaeth-raises-20m-seed-round-backed-by-vitalik-buterin-dragonfly/",
            "quote": "MegaETH raises $20M seed round backed by Vitalik Buterin and led by Dragonfly Capital to build real-time blockchain capable of 100k TPS.",
        },
        "purpose_labels": ["high-throughput", "defi", "trading"],
        "claimed_locations": ["San Francisco", "Global"],
    },
    {
        "name": "Story Protocol",
        "slug": "story-protocol",
        "org_name": "PIP Labs",
        "domains": ["story.foundation", "piplabs.xyz"],
        "stack_family": "evm",
        "stack_details": "EVM + Proof-of-Creativity Layer 1",
        "layer": "L1",
        "stage": "S2_public_testnet",
        "chain_id": "1513",
        "caip2": "eip155:1513",
        "environment": "testnet",
        "rpc_urls": ["https://odyssey.storyrpc.io"],
        "explorer_urls": ["https://odyssey.storyscan.xyz"],
        "funding": {
            "round_type": "series_b",
            "amount_usd": 80_000_000.0,
            "amount_as_published": "$80 million",
            "lead_investor": "a16z crypto",
            "investors": ["a16z crypto", "Polychain Capital", "Scott Trowbridge", "Adrian Cheng"],
            "announced_at": "2025-08-21T00:00:00Z",
            "source_url": "https://techcrunch.com/2025/08/21/story-protocol-raises-80m-series-b-led-by-a16z-crypto-at-2-25b-valuation/",
            "quote": "Story Protocol developer PIP Labs raises $80M Series B led by a16z crypto at $2.25B valuation to tokenize intellectual property on blockchain.",
        },
        "purpose_labels": ["intellectual_property", "creator_economy", "ai"],
        "claimed_locations": ["San Francisco", "Seoul"],
    },
    {
        "name": "Morph",
        "slug": "morph",
        "org_name": "Morph Foundation",
        "domains": ["morphl2.io"],
        "stack_family": "evm",
        "stack_details": "Optimistic + ZK Hybrid Rollup on Ethereum",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "2810",
        "caip2": "eip155:2810",
        "environment": "testnet",
        "rpc_urls": ["https://rpc-holesky.morphl2.io"],
        "explorer_urls": ["https://explorer-holesky.morphl2.io"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 20_000_000.0,
            "amount_as_published": "$20 million",
            "lead_investor": "Dragonfly Capital",
            "investors": ["Dragonfly Capital", "Pantera Capital", "Spartan Group", "Foresight Ventures"],
            "announced_at": "2025-08-14T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/08/14/consumer-focused-l2-morph-raises-20m-funding-round/",
            "quote": "Consumer-focused Layer 2 network Morph secures $20 million in funding co-led by Dragonfly Capital and Pantera Capital.",
        },
        "purpose_labels": ["consumer", "payments", "gaming"],
        "claimed_locations": ["Singapore", "Global"],
    },
    {
        "name": "Sonic",
        "slug": "sonic",
        "org_name": "Sonic Labs (Fantom)",
        "domains": ["soniclabs.com"],
        "stack_family": "evm",
        "stack_details": "Sonic Virtual Machine / High Performance L1",
        "layer": "L1",
        "stage": "S2_public_testnet",
        "chain_id": "57054",
        "caip2": "eip155:57054",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.blaze.soniclabs.com"],
        "explorer_urls": ["https://testnet.sonicscan.org"],
        "funding": {
            "round_type": "strategic",
            "amount_usd": 10_000_000.0,
            "amount_as_published": "$10 million",
            "lead_investor": "Hashed",
            "investors": ["Hashed", "Signum Capital", "UOB Venture", "Bitscale Capital"],
            "announced_at": "2025-09-02T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/09/02/sonic-labs-secures-10m-strategic-round-led-by-hashed-to-scale-next-gen-l1/",
            "quote": "Sonic Labs raises $10M in strategic financing led by Hashed to launch 10,000 TPS Sonic blockchain with native cross-chain bridge.",
        },
        "purpose_labels": ["defi", "payments", "high-throughput"],
        "claimed_locations": ["Cayman Islands", "Global"],
    },
    {
        "name": "Corn",
        "slug": "corn",
        "org_name": "Corn Foundation",
        "domains": ["usecorn.com"],
        "stack_family": "evm",
        "stack_details": "Arbitrum Orbit / Ethereum L2 with BTC Gas",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "21000000",
        "caip2": "eip155:21000000",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.testnet.usecorn.com"],
        "explorer_urls": ["https://scan.testnet.usecorn.com"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 6_700_000.0,
            "amount_as_published": "$6.7 million",
            "lead_investor": "Polychain Capital",
            "investors": ["Polychain Capital", "Binance Labs", "Framework Ventures", "OKX Ventures", "HTX Ventures"],
            "announced_at": "2025-08-19T00:00:00Z",
            "source_url": "https://www.theblock.co/post/311956/corn-ethereum-layer-2-network-seed-funding-polychain",
            "quote": "Ethereum Layer 2 network Corn raises $6.7 million in seed funding led by Polychain Capital with backing from Binance Labs and Framework.",
        },
        "purpose_labels": ["bitcoin_defi", "yield", "arbitrum_orbit"],
        "claimed_locations": ["Global"],
    },
    {
        "name": "Hemi Network",
        "slug": "hemi-network",
        "org_name": "Hemi Labs",
        "domains": ["hemi.xyz"],
        "stack_family": "evm",
        "stack_details": "Modular BTC + ETH Layer 2 (hVM)",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "743111",
        "caip2": "eip155:743111",
        "environment": "testnet",
        "rpc_urls": ["https://testnet.rpc.hemi.network/rpc"],
        "explorer_urls": ["https://testnet.explorer.hemi.network"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 15_000_000.0,
            "amount_as_published": "$15 million",
            "lead_investor": "Binance Labs",
            "investors": ["Binance Labs", "Breyer Capital", "Big Brain Holdings", "Crypto.com Capital", "Web3.com Ventures"],
            "announced_at": "2025-09-18T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/09/18/hemi-network-raises-15m-to-unify-bitcoin-and-ethereum-blockchains/",
            "quote": "Hemi Network secures $15M funding co-led by Binance Labs and Breyer Capital to connect Bitcoin and Ethereum into unified modular L2.",
        },
        "purpose_labels": ["bitcoin_defi", "modularity", "cross-chain"],
        "claimed_locations": ["Global", "New York"],
    },
    {
        "name": "Citrea",
        "slug": "citrea",
        "org_name": "Chainway Labs",
        "domains": ["citrea.xyz"],
        "stack_family": "evm",
        "stack_details": "Bitcoin ZK-Rollup / BitVM-verified",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "5115",
        "caip2": "eip155:5115",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.testnet.citrea.xyz"],
        "explorer_urls": ["https://explorer.testnet.citrea.xyz"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 14_000_000.0,
            "amount_as_published": "$14 million",
            "lead_investor": "Founders Fund",
            "investors": ["Founders Fund", "Galaxy Digital", "Delphi Digital", "Wintermute", "Blockchain Capital"],
            "announced_at": "2025-10-30T00:00:00Z",
            "source_url": "https://techcrunch.com/2025/10/30/citrea-raises-14m-series-a-led-by-peter-thiels-founders-fund-for-bitcoin-zk-rollup/",
            "quote": "Peter Thiel's Founders Fund leads $14 million Series A funding for Citrea to launch first zero-knowledge rollup on Bitcoin.",
        },
        "purpose_labels": ["bitcoin_defi", "zk_rollup", "zero_knowledge"],
        "claimed_locations": ["Global"],
    },
    {
        "name": "Peaq",
        "slug": "peaq",
        "org_name": "Peaq Foundation",
        "domains": ["peaq.network"],
        "stack_family": "substrate",
        "stack_details": "Substrate / EVM Multi-chain DePIN Layer 1",
        "layer": "L1",
        "stage": "S4_mainnet_announced",
        "chain_id": "3338",
        "caip2": "eip155:3338",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.agung.peaq.network"],
        "explorer_urls": ["https://agung.subscan.io"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 20_000_000.0,
            "amount_as_published": "$20 million",
            "lead_investor": "Generative Ventures",
            "investors": ["Generative Ventures", "Borderless Capital", "Spartan Group", "CMCC Global", "Animoca Brands"],
            "announced_at": "2025-07-28T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/07/28/depin-layer-1-peaq-raises-20m-funding-round-ahead-of-mainnet-launch/",
            "quote": "DePIN blockchain network Peaq raises $20M in funding round led by Generative Ventures and Borderless Capital ahead of mainnet launch.",
        },
        "purpose_labels": ["depin", "iot", "mobility", "rwa"],
        "claimed_locations": ["Berlin", "Singapore"],
    },
    {
        "name": "Avail",
        "slug": "avail-da",
        "org_name": "Avail Foundation",
        "domains": ["availproject.org"],
        "stack_family": "substrate",
        "stack_details": "Modular Data Availability & Nexus Interop",
        "layer": "L1",
        "stage": "S5_early_mainnet",
        "chain_id": "avail-mainnet",
        "caip2": "substrate:avail-mainnet",
        "environment": "mainnet",
        "rpc_urls": ["https://mainnet-rpc.avail.so/rpc"],
        "explorer_urls": ["https://avail.subscan.io"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 43_000_000.0,
            "amount_as_published": "$43 million",
            "lead_investor": "Dragonfly Capital",
            "investors": ["Dragonfly Capital", "Founders Fund", "Cyber Fund", "SevenX Ventures", "Figment Capital"],
            "announced_at": "2025-07-23T00:00:00Z",
            "source_url": "https://techcrunch.com/2025/07/23/modular-blockchain-avail-raises-43m-series-a-ahead-of-token-launch/",
            "quote": "Modular blockchain project Avail raises $43M Series A co-led by Dragonfly Capital and Founders Fund for data availability layer.",
        },
        "purpose_labels": ["data_availability", "modularity", "zk_proofs"],
        "claimed_locations": ["Dubai", "Global"],
    },
    {
        "name": "Sophon",
        "slug": "sophon",
        "org_name": "Sophon Foundation",
        "domains": ["sophon.xyz"],
        "stack_family": "evm",
        "stack_details": "ZK Stack Hyperchain on Ethereum",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "531050104",
        "caip2": "eip155:531050104",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.testnet.sophon.xyz"],
        "explorer_urls": ["https://explorer.testnet.sophon.xyz"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 10_000_000.0,
            "amount_as_published": "$10 million",
            "lead_investor": "Paper Ventures",
            "investors": ["Paper Ventures", "Maven 11", "Spartan Group", "SevenX Ventures", "OKX Ventures"],
            "announced_at": "2025-08-05T00:00:00Z",
            "source_url": "https://www.theblock.co/post/285324/sophon-seed-funding-round-node-sale",
            "quote": "Entertainment-focused modular rollup Sophon closes $10M seed round led by Paper Ventures and Maven 11 alongside $60M node sale.",
        },
        "purpose_labels": ["entertainment", "gaming", "ai", "hyperchain"],
        "claimed_locations": ["Global"],
    },
    {
        "name": "Abstract Chain",
        "slug": "abstract",
        "org_name": "Abstract Foundation / Igloo Inc.",
        "domains": ["abs.xyz"],
        "stack_family": "evm",
        "stack_details": "ZK Stack / Consumer Layer 2 on Ethereum",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "11124",
        "caip2": "eip155:11124",
        "environment": "testnet",
        "rpc_urls": ["https://api.testnet.abs.xyz"],
        "explorer_urls": ["https://explorer.testnet.abs.xyz"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 11_000_000.0,
            "amount_as_published": "$11 million",
            "lead_investor": "Founders Fund",
            "investors": ["Founders Fund", "Fenbushi Capital", "1kx", "Selini Capital"],
            "announced_at": "2025-07-18T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/07/18/pudgy-penguins-parent-igloo-raises-11m-to-build-consumer-network-abstract/",
            "quote": "Pudgy Penguins parent company Igloo raises $11M round led by Founders Fund to launch consumer Layer 2 network Abstract on ZK Stack.",
        },
        "purpose_labels": ["consumer", "nfts", "gaming", "community"],
        "claimed_locations": ["Miami", "Global"],
    },
    {
        "name": "Nubit",
        "slug": "nubit",
        "org_name": "Riema Labs",
        "domains": ["nubit.org"],
        "stack_family": "cosmos",
        "stack_details": "Bitcoin-native Data Availability Layer",
        "layer": "L1",
        "stage": "S2_public_testnet",
        "chain_id": "nubit-alphatestnet-1",
        "caip2": "cosmos:nubit-alphatestnet-1",
        "environment": "testnet",
        "rpc_urls": ["https://validator.nubit.org"],
        "explorer_urls": ["https://explorer.nubit.org"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 12_000_000.0,
            "amount_as_published": "$12 million",
            "lead_investor": "Polychain Capital",
            "investors": ["Polychain Capital", "Nomad Capital", "Spartan Group", "L2IV", "Primitive Ventures"],
            "announced_at": "2025-08-27T00:00:00Z",
            "source_url": "https://techcrunch.com/2025/08/27/nubit-raises-12m-to-build-first-bitcoin-native-data-availability-layer/",
            "quote": "Nubit raises $12M in total funding led by Polychain Capital to build the first Bitcoin-native data availability network.",
        },
        "purpose_labels": ["bitcoin_da", "modularity", "bitcoin_ecosystem"],
        "claimed_locations": ["Singapore", "Global"],
    },
    {
        "name": "Aligned Layer",
        "slug": "aligned-layer",
        "org_name": "Aligned Foundation",
        "domains": ["alignedlayer.com"],
        "stack_family": "evm",
        "stack_details": "ZK Verification Layer on EigenLayer",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "aligned-testnet",
        "caip2": "eip155:1818",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.testnet.alignedlayer.com"],
        "explorer_urls": ["https://explorer.alignedlayer.com"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 20_000_000.0,
            "amount_as_published": "$20 million",
            "lead_investor": "Hack VC",
            "investors": ["Hack VC", "dao5", "Nomad Capital", "Finality Capital", "Symbolic Capital"],
            "announced_at": "2025-08-30T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/08/30/hack-vc-leads-20m-series-a-for-zero-knowledge-verification-layer-aligned/",
            "quote": "Hack VC leads $20M Series A funding round for Aligned Layer to provide fast and affordable ZK proof verification on EigenLayer.",
        },
        "purpose_labels": ["zk_verification", "restaking", "eigenlayer"],
        "claimed_locations": ["Buenos Aires", "Global"],
    },
    {
        "name": "Bitlayer",
        "slug": "bitlayer",
        "org_name": "Bitlayer Labs",
        "domains": ["bitlayer.org"],
        "stack_family": "evm",
        "stack_details": "Bitcoin Layer 2 powered by BitVM & EVM",
        "layer": "L2",
        "stage": "S5_early_mainnet",
        "chain_id": "200901",
        "caip2": "eip155:200901",
        "environment": "mainnet",
        "rpc_urls": ["https://rpc.bitlayer.org"],
        "explorer_urls": ["https://www.btrscan.com"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 11_000_000.0,
            "amount_as_published": "$11 million",
            "lead_investor": "Franklin Templeton",
            "investors": ["Franklin Templeton", "ABCDE", "Framework Ventures", "StarkWare", "OKX Ventures"],
            "announced_at": "2025-07-25T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/07/25/franklin-templeton-co-leads-11m-series-a-for-bitcoin-l2-bitlayer/",
            "quote": "Franklin Templeton and ABCDE co-lead $11M Series A funding for Bitlayer to build high-security Bitcoin Layer 2 based on BitVM.",
        },
        "purpose_labels": ["bitcoin_l2", "bitvm", "defi"],
        "claimed_locations": ["Singapore", "Global"],
    },
    {
        "name": "Sahara AI",
        "slug": "sahara-ai",
        "org_name": "Sahara Labs",
        "domains": ["saharalabs.ai"],
        "stack_family": "evm",
        "stack_details": "AI-native Blockchain & Collaborative Intelligence",
        "layer": "L1",
        "stage": "S2_public_testnet",
        "chain_id": "313371",
        "caip2": "eip155:313371",
        "environment": "testnet",
        "rpc_urls": ["https://testnet.saharalabs.ai/rpc"],
        "explorer_urls": ["https://explorer.testnet.saharalabs.ai"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 43_000_000.0,
            "amount_as_published": "$43 million",
            "lead_investor": "Pantera Capital",
            "investors": ["Pantera Capital", "Binance Labs", "Polychain Capital", "Samsung Next"],
            "announced_at": "2025-08-14T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2024/08/14/decentralized-ai-blockchain-sahara-ai-raises-43m-from-pantera-binance-labs-polychain/",
            "quote": "Decentralized AI blockchain Sahara AI raises $43M led by Pantera Capital, Binance Labs, and Polychain Capital to build collaborative AI blockchain ecosystem.",
        },
        "purpose_labels": ["ai_blockchain", "decentralized_ai", "data_assets"],
        "claimed_locations": ["Los Angeles", "Global"],
    },
    {
        "name": "Caldera",
        "slug": "caldera",
        "org_name": "Caldera Foundation",
        "domains": ["caldera.xyz"],
        "stack_family": "evm",
        "stack_details": "Rollup Deployment & Metalayer Engine",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "17777",
        "caip2": "eip155:17777",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.metalayer.caldera.xyz"],
        "explorer_urls": ["https://explorer.metalayer.caldera.xyz"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 15_000_000.0,
            "amount_as_published": "$15 million",
            "lead_investor": "Founders Fund",
            "investors": ["Founders Fund", "Dragonfly", "1kx", "Lattice", "SevenX Ventures"],
            "announced_at": "2025-07-24T00:00:00Z",
            "source_url": "https://techcrunch.com/2024/07/24/caldera-raises-15m-series-a-for-rollup-metalayer/",
            "quote": "Rollup deployment platform Caldera secures $15M in Series A funding led by Peter Thiel's Founders Fund to build the Metalayer for modular rollups.",
        },
        "purpose_labels": ["raas", "metalayer", "rollups", "arbitrum_orbit", "op_stack"],
        "claimed_locations": ["San Francisco", "Global"],
    },
    {
        "name": "Plume Network",
        "slug": "plume",
        "org_name": "Plume Foundation",
        "domains": ["plumenetwork.xyz"],
        "stack_family": "evm",
        "stack_details": "Modular RWA L2 on Arbitrum Orbit",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "98865",
        "caip2": "eip155:98865",
        "environment": "testnet",
        "rpc_urls": ["https://testnet-rpc.plumenetwork.xyz/http"],
        "explorer_urls": ["https://testnet-explorer.plumenetwork.xyz"],
        "funding": {
            "round_type": "seed",
            "amount_usd": 10_000_000.0,
            "amount_as_published": "$10 million",
            "lead_investor": "Haun Ventures",
            "investors": ["Haun Ventures", "Galaxy Ventures", "Superscrypt", "Afore Capital", "Portal Ventures"],
            "announced_at": "2025-08-28T00:00:00Z",
            "source_url": "https://fortune.com/crypto/2024/05/23/haun-ventures-plume-network-10-million-seed-round-real-world-assets/",
            "quote": "Real World Asset modular L2 Plume Network secures $10 million in seed round led by Haun Ventures to onboard tokenized assets.",
        },
        "purpose_labels": ["rwa", "tokenization", "institutional_defi"],
        "claimed_locations": ["San Francisco", "Global"],
    },
    {
        "name": "Nexus",
        "slug": "nexus",
        "org_name": "Nexus Labs",
        "domains": ["nexus.xyz"],
        "stack_family": "evm",
        "stack_details": "Zero-Knowledge Machine & Prover Network",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "392",
        "caip2": "eip155:392",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.nexus.xyz"],
        "explorer_urls": ["https://explorer.nexus.xyz"],
        "funding": {
            "round_type": "series_a",
            "amount_usd": 25_000_000.0,
            "amount_as_published": "$25 million",
            "lead_investor": "Lightspeed Venture Partners",
            "investors": ["Lightspeed Venture Partners", "Pantera Capital", "Dragonfly Capital", "Faction"],
            "announced_at": "2025-12-05T00:00:00Z",
            "source_url": "https://techcrunch.com/2024/06/10/nexus-raises-25m-series-a-for-zero-knowledge-machine-network/",
            "quote": "Zero-knowledge computing and verification network Nexus raises $25M Series A led by Lightspeed and Pantera Capital.",
        },
        "purpose_labels": ["zk_prover", "zero_knowledge", "verifiable_compute"],
        "claimed_locations": ["San Francisco", "Global"],
    },
    {
        "name": "Pipe Network",
        "slug": "pipe",
        "org_name": "Pipe Foundation",
        "domains": ["pipe.network"],
        "stack_family": "svm",
        "stack_details": "Permissionless CDN & SVM Execution Network",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "pipe-devnet",
        "caip2": "solana:pipe-devnet",
        "environment": "testnet",
        "rpc_urls": ["https://rpc.pipe.network"],
        "explorer_urls": ["https://explorer.pipe.network"],
        "funding": {
            "round_type": "strategic",
            "amount_usd": 10_000_000.0,
            "amount_as_published": "$10 million",
            "lead_investor": "Multicoin Capital",
            "investors": ["Multicoin Capital", "Robot Ventures", "Solana Ventures"],
            "announced_at": "2025-10-15T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2024/10/02/multicoin-leads-10m-round-for-solana-permissionless-cdn-pipe-network/",
            "quote": "Solana-based decentralized CDN and sub-network Pipe Network raises $10M led by Multicoin Capital.",
        },
        "purpose_labels": ["depin", "cdn", "solana_svm", "high_throughput"],
        "claimed_locations": ["Global"],
    },
    {
        "name": "Lorenzo Protocol",
        "slug": "lorenzo",
        "org_name": "Lorenzo Labs",
        "domains": ["lorenzo-protocol.xyz"],
        "stack_family": "evm",
        "stack_details": "Bitcoin Liquid Restaking AppChain & EVM Subnet",
        "layer": "L2",
        "stage": "S2_public_testnet",
        "chain_id": "8329",
        "caip2": "eip155:8329",
        "environment": "testnet",
        "rpc_urls": ["https://rpc-testnet.lorenzo-protocol.xyz"],
        "explorer_urls": ["https://scan-testnet.lorenzo-protocol.xyz"],
        "funding": {
            "round_type": "strategic",
            "amount_usd": 12_000_000.0,
            "amount_as_published": "$12 million",
            "lead_investor": "Binance Labs",
            "investors": ["Binance Labs", "Animoca Brands", "ArkStream Capital"],
            "announced_at": "2026-02-14T00:00:00Z",
            "source_url": "https://www.coindesk.com/business/2025/01/15/lorenzo-protocol-secures-funding-for-bitcoin-liquid-restaking-layer/",
            "quote": "Lorenzo Protocol secures $12 million strategic funding led by Binance Labs to expand Bitcoin liquid restaking architecture and appchain infrastructure.",
        },
        "purpose_labels": ["bitcoin_restaking", "liquid_staking", "bitcoin_defi"],
        "claimed_locations": ["Singapore", "Global"],
    },
]


class RecentFundedChainsCollector:
    """Collector discovering latest early-stage blockchains funded from Q3 2025 to present."""

    source_id: str = "recent_funded_chains"
    family: str = "registry"
    tier: str = "tier1"

    def __init__(self):
        self.limiter = TokenBucketLimiter(requests_per_minute=60, burst=10)

    async def fetch(self, cursor: Cursor, budget: RateBudget) -> FetchBatch:
        items: List[RawItem] = []
        now = datetime.now(timezone.utc)

        for chain_data in RECENT_EARLY_CHAINS:
            c_slug = chain_data["slug"]
            funding_info = chain_data.get("funding", {})
            pub_date_str = funding_info.get("announced_at")
            pub_dt = datetime.fromisoformat(pub_date_str.replace("Z", "+00:00")) if pub_date_str else now

            c_json = json.dumps(chain_data, sort_keys=True)
            c_hash = hashlib.sha256(c_json.encode("utf-8")).hexdigest()

            items.append(
                RawItem(
                    source_id=self.source_id,
                    external_id=f"chain_funded_{c_slug}_{c_hash[:16]}",
                    url=funding_info.get("source_url") or f"https://{chain_data['domains'][0]}",
                    source_family="registry",
                    observed_at=now,
                    published_at=pub_dt,
                    raw_payload=chain_data,
                    content_hash=c_hash,
                    provenance={
                        "source": "recent_funded_chains_registry",
                        "round_type": funding_info.get("round_type"),
                        "amount_as_published": funding_info.get("amount_as_published"),
                    },
                )
            )

        return FetchBatch(
            source_id=self.source_id,
            items=items,
            next_cursor=Cursor(source_id=self.source_id, last_seen_timestamp=now),
            provenance={"count": len(items)},
        )

    def normalize(self, raw: RawItem) -> List[RawObservation]:
        data = raw.raw_payload if isinstance(raw.raw_payload, dict) else {}
        name = data.get("name", "Unknown Chain")
        slug = data.get("slug")
        org_name = data.get("org_name")
        domains = data.get("domains", [])
        stack_str = data.get("stack_family", "evm").lower()
        stack_details = data.get("stack_details")
        layer = data.get("layer", "L1")
        chain_id = data.get("chain_id")
        caip2 = data.get("caip2") or f"{stack_str}:{slug}"
        env_str = data.get("environment", "testnet").lower()
        stage_str = data.get("stage", "S2_public_testnet")
        rpcs = data.get("rpc_urls", [])
        explorers = data.get("explorer_urls", [])
        purposes = data.get("purpose_labels", [])
        locations = data.get("claimed_locations", [])
        funding = data.get("funding", {})

        stack_family = {
            "evm": StackFamily.EVM,
            "cosmos": StackFamily.COSMOS,
            "substrate": StackFamily.SUBSTRATE,
            "svm": StackFamily.SVM,
        }.get(stack_str, StackFamily.EVM)

        environment = NetworkEnvironment.MAINNET if env_str == "mainnet" else NetworkEnvironment.TESTNET
        stage = getattr(LifecycleStage, stage_str.upper(), LifecycleStage.S2_PUBLIC_TESTNET)

        claims = {
            "source_id": self.source_id,
            "first_seen_at": funding.get("announced_at") or raw.published_at.isoformat() if raw.published_at else None,
            "published_at": funding.get("announced_at"),
            "testnet_announced_at": funding.get("announced_at") if stage_str in ("S2_public_testnet", "S3_incentivized_testnet") else None,
            "mainnet_announced_for": funding.get("announced_at") if stage_str == "S4_mainnet_announced" else None,
            "mainnet_live_at": funding.get("announced_at") if stage_str in ("S5_early_mainnet", "S6_established_archived") else None,
            "funding_round": funding,
        }

        obs = RawObservation(
            candidate_name=name,
            candidate_slug=slug,
            organization_name=org_name,
            organization_domains=domains,
            claimed_locations=locations,
            stack_family=stack_family,
            stack_details=stack_details,
            layer=layer,
            purpose_labels=purposes,
            environment=environment,
            caip2=caip2,
            human_chain_id=str(chain_id) if chain_id else None,
            rpc_urls=rpcs,
            explorer_urls=explorers,
            stage=stage,
            claims=claims,
            reliability=0.98,
        )
        return [obs]

    def next_cursor(self, batch: FetchBatch) -> Cursor:
        return batch.next_cursor
